favicon: null
name: HypNoise
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5157378
  lightness: 0.4535867
  brandStrength: 0.7097490183077753
  brandColors:
    - '#C5DFE9'
    - '#38311E'
    - '#5377A3'
    - '#A3B5C4'
    - '#435365'
  rhythmicContrast: 0.5425532
typography_spectrum: 0.1978723
layout_spectrum: 0.1086215141694993
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
